######################################################################
# Automatically generated by qmake (3.0) Thu Aug 4 07:37:45 2016
######################################################################

TEMPLATE = app
TARGET = qthello
INCLUDEPATH += .

# Input
SOURCES += qthello.cpp
QT += core widgets gui
